# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from optimus_proto import optimus_pb2 as optimus__pb2


class OptimusStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreatePoint = channel.unary_unary(
        '/Optimus/CreatePoint',
        request_serializer=optimus__pb2.Point.SerializeToString,
        response_deserializer=optimus__pb2.Point.FromString,
        )
    self.GetPoint = channel.unary_unary(
        '/Optimus/GetPoint',
        request_serializer=optimus__pb2.RequestWithId.SerializeToString,
        response_deserializer=optimus__pb2.Point.FromString,
        )
    self.ListPoints = channel.unary_unary(
        '/Optimus/ListPoints',
        request_serializer=optimus__pb2.ListPointsRequest.SerializeToString,
        response_deserializer=optimus__pb2.ListOfPoints.FromString,
        )
    self.ModifyPoint = channel.unary_unary(
        '/Optimus/ModifyPoint',
        request_serializer=optimus__pb2.Point.SerializeToString,
        response_deserializer=optimus__pb2.Point.FromString,
        )


class OptimusServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreatePoint(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPoint(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListPoints(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ModifyPoint(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OptimusServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreatePoint': grpc.unary_unary_rpc_method_handler(
          servicer.CreatePoint,
          request_deserializer=optimus__pb2.Point.FromString,
          response_serializer=optimus__pb2.Point.SerializeToString,
      ),
      'GetPoint': grpc.unary_unary_rpc_method_handler(
          servicer.GetPoint,
          request_deserializer=optimus__pb2.RequestWithId.FromString,
          response_serializer=optimus__pb2.Point.SerializeToString,
      ),
      'ListPoints': grpc.unary_unary_rpc_method_handler(
          servicer.ListPoints,
          request_deserializer=optimus__pb2.ListPointsRequest.FromString,
          response_serializer=optimus__pb2.ListOfPoints.SerializeToString,
      ),
      'ModifyPoint': grpc.unary_unary_rpc_method_handler(
          servicer.ModifyPoint,
          request_deserializer=optimus__pb2.Point.FromString,
          response_serializer=optimus__pb2.Point.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Optimus', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
